=== pleuston/eXistcbdb/accessfiles/CHORONYM_CODES.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="dataroot">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="CHORONYM_CODES" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="generated" type="xsd:dateTime"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="CHORONYM_CODES">
        <xsd:annotation>
            <xsd:appinfo>
                <od:index index-name="PrimaryKey" index-key="c_choronym_code " primary="yes" unique="yes" clustered="no" order="asc"/>
                <od:tableProperty name="Orientation" type="2" value="0"/>
                <od:tableProperty name="OrderByOn" type="1" value="0"/>
                <od:tableProperty name="NameMap" type="11" value="CswOVQAAAAB2udYLKm/PR7TjS8GFKawkAAAAADT8uy7+SeRAAAAAAAAAAABDAEgA TwBSAE8ATgBZAE0AXwBDAE8ARABFAFMAAAAAAAAAVK8AUK/nXkyXm3xlr2f9GQcA AAB2udYLKm/PR7TjS8GFKawkYwBfAGMAaABvAHIAbwBuAHkAbQBfAGMAbwBkAGUA AAAAAAAA9xVF65QkLUav/mjK+P1+5gcAAAB2udYLKm/PR7TjS8GFKawkYwBfAGMA aABvAHIAbwBuAHkAbQBfAGQAZQBzAGMAAAAAAAAAs4dPBB0DLkSsPxGQ6o6AMgcA AAB2udYLKm/PR7TjS8GFKawkYwBfAGMAaABvAHIAbwBuAHkAbQBfAGMAaABuAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABQAAAAAAAAAAAAAAAAAAAAAA "/>
                <od:tableProperty name="DefaultView" type="2" value="2"/>
                <od:tableProperty name="GUID" type="9" value="drnWCypvz0e040vBhSmsJA== "/>
                <od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
                <od:tableProperty name="TotalsRow" type="1" value="0"/>
                <od:tableProperty name="FilterOnLoad" type="1" value="0"/>
                <od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
                <od:tableProperty name="HideNewField" type="1" value="0"/>
                <od:tableProperty name="BackTint" type="6" value="100"/>
                <od:tableProperty name="BackShade" type="6" value="100"/>
                <od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
                <od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
                <od:tableProperty name="AlternateBackTint" type="6" value="100"/>
                <od:tableProperty name="AlternateBackShade" type="6" value="100"/>
                <od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
                <od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="c_choronym_code" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="GUID" type="9" value="VK8AUK/nXkyXm3xlr2f9GQ== "/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="c_choronym_desc" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="IMEMode" type="2" value="1"/>
                            <od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
                            <od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
                            <od:fieldProperty name="GUID" type="9" value="9xVF65QkLUav/mjK+P1+5g== "/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:maxLength value="255"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="c_choronym_chn" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="IMEMode" type="2" value="1"/>
                            <od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
                            <od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
                            <od:fieldProperty name="GUID" type="9" value="s4dPBB0DLkSsPxGQ6o6AMg== "/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:maxLength value="255"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== pleuston/eXistcbdb/accessfiles/CHORONYM_CODES.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CHORONYM_CODES.xsd" generated="2013-11-25T16:36:12">
    <CHORONYM_CODES>
        <c_choronym_code>0</c_choronym_code>
        <c_choronym_desc>[Unknown]</c_choronym_desc>
        <c_choronym_chn>【未詳】</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>1</c_choronym_code>
        <c_choronym_desc>Anding</c_choronym_desc>
        <c_choronym_chn>安定</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>2</c_choronym_code>
        <c_choronym_desc>Chenliu</c_choronym_desc>
        <c_choronym_chn>陳留</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>3</c_choronym_code>
        <c_choronym_desc>Qiantang</c_choronym_desc>
        <c_choronym_chn>錢塘</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>4</c_choronym_code>
        <c_choronym_desc>Qinghe</c_choronym_desc>
        <c_choronym_chn>清河</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>6</c_choronym_code>
        <c_choronym_desc>Fanyang</c_choronym_desc>
        <c_choronym_chn>范陽</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>7</c_choronym_code>
        <c_choronym_desc>Peiguo</c_choronym_desc>
        <c_choronym_chn>沛國</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>8</c_choronym_code>
        <c_choronym_desc>Henei</c_choronym_desc>
        <c_choronym_chn>河內</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>9</c_choronym_code>
        <c_choronym_desc>Hongnong</c_choronym_desc>
        <c_choronym_chn>弘農</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>10</c_choronym_code>
        <c_choronym_desc>Runan</c_choronym_desc>
        <c_choronym_chn>汝南</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>11</c_choronym_code>
        <c_choronym_desc>Xingyang</c_choronym_desc>
        <c_choronym_chn>滎陽</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>12</c_choronym_code>
        <c_choronym_desc>Gaoping</c_choronym_desc>
        <c_choronym_chn>高平</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>13</c_choronym_code>
        <c_choronym_desc>Lean</c_choronym_desc>
        <c_choronym_chn>樂安</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>14</c_choronym_code>
        <c_choronym_desc>Luguo</c_choronym_desc>
        <c_choronym_chn>魯國</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>15</c_choronym_code>
        <c_choronym_desc>Longxi</c_choronym_desc>
        <c_choronym_chn>隴西</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>16</c_choronym_code>
        <c_choronym_desc>Nanyang</c_choronym_desc>
        <c_choronym_chn>南陽</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>17</c_choronym_code>
        <c_choronym_desc>Pengcheng</c_choronym_desc>
        <c_choronym_chn>彭城</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>18</c_choronym_code>
        <c_choronym_desc>Song Taizu</c_choronym_desc>
        <c_choronym_chn>宋太祖</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>19</c_choronym_code>
        <c_choronym_desc>Song Taizong</c_choronym_desc>
        <c_choronym_chn>宋太宗</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>20</c_choronym_code>
        <c_choronym_desc>Taiyuan</c_choronym_desc>
        <c_choronym_chn>太原</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>21</c_choronym_code>
        <c_choronym_desc>Waiqi</c_choronym_desc>
        <c_choronym_chn>外戚[刪]</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>22</c_choronym_code>
        <c_choronym_desc>Weiwang</c_choronym_desc>
        <c_choronym_chn>魏王</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>23</c_choronym_code>
        <c_choronym_desc>Wujun</c_choronym_desc>
        <c_choronym_chn>吳郡</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>24</c_choronym_code>
        <c_choronym_desc>Wuxing</c_choronym_desc>
        <c_choronym_chn>吳興</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>25</c_choronym_code>
        <c_choronym_desc>Wugong</c_choronym_desc>
        <c_choronym_chn>武功</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>26</c_choronym_code>
        <c_choronym_desc>Wuyue</c_choronym_desc>
        <c_choronym_chn>吳越</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>27</c_choronym_code>
        <c_choronym_desc>Yuzhang</c_choronym_desc>
        <c_choronym_chn>豫章</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>28</c_choronym_code>
        <c_choronym_desc>Zhaojun</c_choronym_desc>
        <c_choronym_chn>趙郡</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>29</c_choronym_code>
        <c_choronym_desc>Jingzhao</c_choronym_desc>
        <c_choronym_chn>京兆</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>30</c_choronym_code>
        <c_choronym_desc>Fufeng</c_choronym_desc>
        <c_choronym_chn>扶風</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>31</c_choronym_code>
        <c_choronym_desc>Dongping</c_choronym_desc>
        <c_choronym_chn>東平</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>32</c_choronym_code>
        <c_choronym_desc>Dongyang</c_choronym_desc>
        <c_choronym_chn>東陽</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>33</c_choronym_code>
        <c_choronym_desc>Wuwei</c_choronym_desc>
        <c_choronym_chn>武威</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>34</c_choronym_code>
        <c_choronym_desc>Hedong</c_choronym_desc>
        <c_choronym_chn>河東</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>36</c_choronym_code>
        <c_choronym_desc>Zhongshan</c_choronym_desc>
        <c_choronym_chn>中山</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>37</c_choronym_code>
        <c_choronym_desc>Fengyi</c_choronym_desc>
        <c_choronym_chn>馮翊</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>38</c_choronym_code>
        <c_choronym_desc>Guangling</c_choronym_desc>
        <c_choronym_chn>廣陵</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>39</c_choronym_code>
        <c_choronym_desc>Langye</c_choronym_desc>
        <c_choronym_chn>琅琊</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>41</c_choronym_code>
        <c_choronym_desc>Pingyang</c_choronym_desc>
        <c_choronym_chn>平陽</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>42</c_choronym_code>
        <c_choronym_desc>Bohai</c_choronym_desc>
        <c_choronym_chn>渤海</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>43</c_choronym_code>
        <c_choronym_desc>Tianshui</c_choronym_desc>
        <c_choronym_chn>天水</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>45</c_choronym_code>
        <c_choronym_desc>Yingchuan</c_choronym_desc>
        <c_choronym_chn>穎川</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>46</c_choronym_code>
        <c_choronym_desc>Xihe</c_choronym_desc>
        <c_choronym_chn>西河</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>47</c_choronym_code>
        <c_choronym_desc>Qiaoguo</c_choronym_desc>
        <c_choronym_chn>譙國</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>48</c_choronym_code>
        <c_choronym_desc>Henan</c_choronym_desc>
        <c_choronym_chn>河南</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>49</c_choronym_code>
        <c_choronym_desc>Jijun</c_choronym_desc>
        <c_choronym_chn>汲郡</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>51</c_choronym_code>
        <c_choronym_desc>Hejian</c_choronym_desc>
        <c_choronym_chn>河間</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>53</c_choronym_code>
        <c_choronym_desc>Guangping</c_choronym_desc>
        <c_choronym_chn>廣平</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>55</c_choronym_code>
        <c_choronym_desc>Wuchang</c_choronym_desc>
        <c_choronym_chn>武昌</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>57</c_choronym_code>
        <c_choronym_desc>Puyang</c_choronym_desc>
        <c_choronym_chn>濮陽</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>58</c_choronym_code>
        <c_choronym_desc>Julu</c_choronym_desc>
        <c_choronym_chn>鉅鹿</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>59</c_choronym_code>
        <c_choronym_desc>Shiping</c_choronym_desc>
        <c_choronym_chn>始平</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
        <c_choronym_code>61</c_choronym_code>
        <c_choronym_desc>Jiyang</c_choronym_desc>
        <c_choronym_chn>濟陽</c_choronym_chn>
    </CHORONYM_CODES>
    <CHORONYM_CODES>
