=== pleuston/eXistcbdb/accessfiles/DYNASTIES.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="dataroot">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="DYNASTIES" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="generated" type="xsd:dateTime"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="DYNASTIES">
        <xsd:annotation>
            <xsd:appinfo>
                <od:index index-name="PrimaryKey" index-key="c_dy " primary="yes" unique="yes" clustered="no" order="asc"/>
                <od:tableProperty name="Orientation" type="2" value="0"/>
                <od:tableProperty name="OrderByOn" type="1" value="1"/>
                <od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAuDYndWXmTRZvOu/PhB6OvAAAAAOj3c+4Yo+NAmCQSAONi3XVEAFkA TgBBAFMAVABJAEUAUwAAAAAAAACLo5RnTPd7Rqf6FZqRSsJeBwAAAC4Nid1ZeZNF m8678+EHo69jAF8AZAB5AAAAAAAAAE99F1uti1BOiiFc9VkTXVYHAAAALg2J3Vl5 k0Wbzrvz4Qejr2MAXwBkAHkAbgBhAHMAdAB5AAAAAAAAAIhwUulHvrRBmR3qdkHJ tK0HAAAALg2J3Vl5k0Wbzrvz4Qejr2MAXwBkAHkAbgBhAHMAdAB5AF8AYwBoAG4A AAAAAAAA4SzvjPc7PUydJbE62rf6gwcAAAAuDYndWXmTRZvOu/PhB6OvYwBfAHMA dABhAHIAdAAAAAAAAAAvXJFE+uatQqdtchoGDViwBwAAAC4Nid1ZeZNFm8678+EH o69jAF8AZQBuAGQAAAAAAAAAGp6YBUjl2UitW4f6SsjiXwcAAAAuDYndWXmTRZvO u/PhB6OvYwBfAHMAbwByAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAADAAAA AAAAAAAAAAAAAAAAAAA= "/>
                <od:tableProperty name="DefaultView" type="2" value="2"/>
                <od:tableProperty name="GUID" type="9" value="Lg2J3Vl5k0Wbzrvz4Qejrw== "/>
                <od:tableProperty name="OrderBy" type="12" value="DYNASTIES.c_dy"/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="c_dy" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="GUID" type="9" value="i6OUZ0z3e0an+hWakUrCXg== "/>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="c_dynasty" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="IMEMode" type="2" value="1"/>
                            <od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
                            <od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
                            <od:fieldProperty name="GUID" type="9" value="T30XW62LUE6KIVz1WRNdVg== "/>
                        </xsd:appinfo>
                    </xsd:annotation>
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:maxLength value="255"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="c_dynasty_chn" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="IMEMode" type="2" value="1"/>
                            <od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
                            <od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
                            <od:fieldProperty name="GUID" type="9" value="iHBS6Ue+tEGZHep2Qcm0rQ== "/>
                        </xsd:appinfo>
                    </xsd:annotation>
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:maxLength value="255"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="c_start" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="GUID" type="9" value="4SzvjPc7PUydJbE62rf6gw== "/>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="c_end" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="GUID" type="9" value="L1yRRPrmrUKnbXIaBg1YsA== "/>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="c_sort" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="GUID" type="9" value="Gp6YBUjl2UitW4f6SsjiXw== "/>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== pleuston/eXistcbdb/accessfiles/DYNASTIES.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DYNASTIES.xsd" generated="2013-11-25T16:38:04">
    <DYNASTIES>
        <c_dy>0</c_dy>
        <c_dynasty>unknown</c_dynasty>
        <c_dynasty_chn>未詳</c_dynasty_chn>
        <c_start>0</c_start>
        <c_end>0</c_end>
        <c_sort>0</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>1</c_dy>
        <c_dynasty>Pre-Han</c_dynasty>
        <c_dynasty_chn>漢前</c_dynasty_chn>
        <c_start>-1100</c_start>
        <c_end>-206</c_end>
        <c_sort>1</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>2</c_dy>
        <c_dynasty>QinHan</c_dynasty>
        <c_dynasty_chn>秦漢</c_dynasty_chn>
        <c_start>-221</c_start>
        <c_end>220</c_end>
        <c_sort>2</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>3</c_dy>
        <c_dynasty>SanGuo</c_dynasty>
        <c_dynasty_chn>三國</c_dynasty_chn>
        <c_start>220</c_start>
        <c_end>265</c_end>
        <c_sort>7</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>4</c_dy>
        <c_dynasty>NanBei Chao</c_dynasty>
        <c_dynasty_chn>南北朝</c_dynasty_chn>
        <c_start>420</c_start>
        <c_end>589</c_end>
        <c_sort>13</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>5</c_dy>
        <c_dynasty>Sui</c_dynasty>
        <c_dynasty_chn>隋</c_dynasty_chn>
        <c_start>581</c_start>
        <c_end>618</c_end>
        <c_sort>41</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>6</c_dy>
        <c_dynasty>Tang</c_dynasty>
        <c_dynasty_chn>唐</c_dynasty_chn>
        <c_start>618</c_start>
        <c_end>907</c_end>
        <c_sort>42</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>7</c_dy>
        <c_dynasty>Five Dynasties</c_dynasty>
        <c_dynasty_chn>五代</c_dynasty_chn>
        <c_start>907</c_start>
        <c_end>960</c_end>
        <c_sort>44</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>8</c_dy>
        <c_dynasty>Later Shu (10 states)</c_dynasty>
        <c_dynasty_chn>後蜀</c_dynasty_chn>
        <c_start>933</c_start>
        <c_end>965</c_end>
        <c_sort>52</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>9</c_dy>
        <c_dynasty>Wu</c_dynasty>
        <c_dynasty_chn>吳</c_dynasty_chn>
        <c_start>904</c_start>
        <c_end>937</c_end>
        <c_sort>77</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>10</c_dy>
        <c_dynasty>Southern Tang (10 states)</c_dynasty>
        <c_dynasty_chn>南唐</c_dynasty_chn>
        <c_start>937</c_start>
        <c_end>975</c_end>
        <c_sort>58</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>11</c_dy>
        <c_dynasty>WuYue (10 states)</c_dynasty>
        <c_dynasty_chn>吳越</c_dynasty_chn>
        <c_start>907</c_start>
        <c_end>978</c_end>
        <c_sort>53</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>12</c_dy>
        <c_dynasty>Min (10 states)</c_dynasty>
        <c_dynasty_chn>閩國</c_dynasty_chn>
        <c_start>909</c_start>
        <c_end>945</c_end>
        <c_sort>55</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>13</c_dy>
        <c_dynasty>Southern Han (10 states)</c_dynasty>
        <c_dynasty_chn>南漢</c_dynasty_chn>
        <c_start>917</c_start>
        <c_end>971</c_end>
        <c_sort>56</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>14</c_dy>
        <c_dynasty>Koryo</c_dynasty>
        <c_dynasty_chn>高麗</c_dynasty_chn>
        <c_start>0</c_start>
        <c_end>0</c_end>
        <c_sort>74</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>15</c_dy>
        <c_dynasty>Song</c_dynasty>
        <c_dynasty_chn>宋</c_dynasty_chn>
        <c_start>960</c_start>
        <c_end>1279</c_end>
        <c_sort>61</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>16</c_dy>
        <c_dynasty>Liao</c_dynasty>
        <c_dynasty_chn>遼</c_dynasty_chn>
        <c_start>947</c_start>
        <c_end>1115</c_end>
        <c_sort>60</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>17</c_dy>
        <c_dynasty>Jin</c_dynasty>
        <c_dynasty_chn>金</c_dynasty_chn>
        <c_start>1115</c_start>
        <c_end>1234</c_end>
        <c_sort>63</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>18</c_dy>
        <c_dynasty>Yuan</c_dynasty>
        <c_dynasty_chn>元</c_dynasty_chn>
        <c_start>1234</c_start>
        <c_end>1367</c_end>
        <c_sort>66</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>19</c_dy>
        <c_dynasty>Ming</c_dynasty>
        <c_dynasty_chn>明</c_dynasty_chn>
        <c_start>1368</c_start>
        <c_end>1644</c_end>
        <c_sort>68</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>20</c_dy>
        <c_dynasty>Qing</c_dynasty>
        <c_dynasty_chn>清</c_dynasty_chn>
        <c_start>1644</c_start>
        <c_end>1911</c_end>
        <c_sort>69</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>21</c_dy>
        <c_dynasty>Republic of China</c_dynasty>
        <c_dynasty_chn>中華民國</c_dynasty_chn>
        <c_start>1912</c_start>
        <c_end>3000</c_end>
        <c_sort>70</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>22</c_dy>
        <c_dynasty>People's Republic of China</c_dynasty>
        <c_dynasty_chn>中華人民共和國</c_dynasty_chn>
        <c_start>1949</c_start>
        <c_end>3000</c_end>
        <c_sort>71</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>23</c_dy>
        <c_dynasty>Western Jin</c_dynasty>
        <c_dynasty_chn>西晉</c_dynasty_chn>
        <c_start>265</c_start>
        <c_end>316</c_end>
        <c_sort>11</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>24</c_dy>
        <c_dynasty>Chen</c_dynasty>
        <c_dynasty_chn>陳</c_dynasty_chn>
        <c_start>557</c_start>
        <c_end>589</c_end>
        <c_sort>17</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>25</c_dy>
        <c_dynasty>Eastern Han</c_dynasty>
        <c_dynasty_chn>東漢</c_dynasty_chn>
        <c_start>25</c_start>
        <c_end>220</c_end>
        <c_sort>6</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>26</c_dy>
        <c_dynasty>SanGuo Wei</c_dynasty>
        <c_dynasty_chn>三國魏</c_dynasty_chn>
        <c_start>220</c_start>
        <c_end>265</c_end>
        <c_sort>8</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>27</c_dy>
        <c_dynasty>Eastern Jin</c_dynasty>
        <c_dynasty_chn>東晉</c_dynasty_chn>
        <c_start>317</c_start>
        <c_end>419</c_end>
        <c_sort>12</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>28</c_dy>
        <c_dynasty>Song (Liu)</c_dynasty>
        <c_dynasty_chn>宋(劉)</c_dynasty_chn>
        <c_start>420</c_start>
        <c_end>479</c_end>
        <c_sort>14</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>29</c_dy>
        <c_dynasty>Western Han</c_dynasty>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_start>-206</c_start>
        <c_end>9</c_end>
        <c_sort>4</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>30</c_dy>
        <c_dynasty>Northern Wei</c_dynasty>
        <c_dynasty_chn>北魏</c_dynasty_chn>
        <c_start>386</c_start>
        <c_end>534</c_end>
        <c_sort>18</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>31</c_dy>
        <c_dynasty>Northern Zhou</c_dynasty>
        <c_dynasty_chn>北周</c_dynasty_chn>
        <c_start>557</c_start>
        <c_end>581</c_end>
        <c_sort>22</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>32</c_dy>
        <c_dynasty>Southern Qi</c_dynasty>
        <c_dynasty_chn>南齌</c_dynasty_chn>
        <c_start>479</c_start>
        <c_end>502</c_end>
        <c_sort>15</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>34</c_dy>
        <c_dynasty>Later Liang (5 dynasties)</c_dynasty>
        <c_dynasty_chn>後梁</c_dynasty_chn>
        <c_start>907</c_start>
        <c_end>923</c_end>
        <c_sort>45</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>35</c_dy>
        <c_dynasty>Northern Qi</c_dynasty>
        <c_dynasty_chn>北齊</c_dynasty_chn>
        <c_start>550</c_start>
        <c_end>578</c_end>
        <c_sort>21</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>36</c_dy>
        <c_dynasty>Wu (Yang: 10 states)</c_dynasty>
        <c_dynasty_chn>吳(楊)</c_dynasty_chn>
        <c_start>904</c_start>
        <c_end>937</c_end>
        <c_sort>50</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>37</c_dy>
        <c_dynasty>Minor Liang</c_dynasty>
        <c_start>0</c_start>
        <c_end>0</c_end>
        <c_sort>75</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>38</c_dy>
        <c_dynasty>Chu (Ma:10 states)</c_dynasty>
        <c_dynasty_chn>楚(馬)</c_dynasty_chn>
        <c_start>907</c_start>
        <c_end>951</c_end>
        <c_sort>54</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>39</c_dy>
        <c_dynasty>Former Yan (16 states)</c_dynasty>
        <c_dynasty_chn>前燕</c_dynasty_chn>
        <c_start>337</c_start>
        <c_end>370</c_end>
        <c_sort>28</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>40</c_dy>
        <c_dynasty>Western Wei</c_dynasty>
        <c_dynasty_chn>西魏</c_dynasty_chn>
        <c_start>535</c_start>
        <c_end>557</c_end>
        <c_sort>20</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>41</c_dy>
        <c_dynasty>Eastern Wei</c_dynasty>
        <c_dynasty_chn>東魏</c_dynasty_chn>
        <c_start>534</c_start>
        <c_end>550</c_end>
        <c_sort>19</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>42</c_dy>
        <c_dynasty>SanGuo Wu</c_dynasty>
        <c_dynasty_chn>三國吳</c_dynasty_chn>
        <c_start>222</c_start>
        <c_end>280</c_end>
        <c_sort>10</c_sort>
    </DYNASTIES>
    <DYNASTIES>
        <c_dy>43</c_dy>
        <c_dynasty>Qin</c_dynasty>
        <c_dynasty_chn>秦</c_dynasty_chn>
        <c_start>0</c_start>
        <c_end>0</c_end>
        <c_sort>76</c_sort>
    </DYNASTIES>
