=== pleuston/eXistcbdb/accessfiles/HOUSEHOLD_STATUS_CODES.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="dataroot">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="HOUSEHOLD_STATUS_CODES" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="generated" type="xsd:dateTime"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="HOUSEHOLD_STATUS_CODES">
        <xsd:annotation>
            <xsd:appinfo>
                <od:index index-name="c_household_status_code" index-key="c_household_status_code " primary="no" unique="no" clustered="no" order="asc"/>
                <od:index index-name="PrimaryKey" index-key="c_household_status_code " primary="yes" unique="yes" clustered="no" order="asc"/>
                <od:tableProperty name="GUID" type="9" value="6NVU9trggUCSUEMf1DI8fw== "/>
                <od:tableProperty name="Orientation" type="2" value="0"/>
                <od:tableProperty name="OrderByOn" type="1" value="0"/>
                <od:tableProperty name="NameMap" type="11" value="CswOVQAAAADo1VT22uCBQJJQQx/UMjx/AAAAAMOnnIguP+RAAAAAAAAAAABIAE8A VQBTAEUASABPAEwARABfAFMAVABBAFQAVQBTAF8AQwBPAEQARQBTAAAAAAAAAGbK 8+wVLBFHpJR1SAXI+mYHAAAA6NVU9trggUCSUEMf1DI8f2MAXwBoAG8AdQBzAGUA aABvAGwAZABfAHMAdABhAHQAdQBzAF8AYwBvAGQAZQAAAAAAAADpiGxZc6EvQYzX Yhy0JsarBwAAAOjVVPba4IFAklBDH9QyPH9jAF8AaABvAHUAcwBlAGgAbwBsAGQA XwBzAHQAYQB0AHUAcwBfAGQAZQBzAGMAAAAAAAAAUMvW04lKfEWLj6D7NUeiIgcA AADo1VT22uCBQJJQQx/UMjx/YwBfAGgAbwB1AHMAZQBoAG8AbABkAF8AcwB0AGEA dAB1AHMAXwBkAGUAcwBjAF8AYwBoAG4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwA AAAFAAAAAAAAAAAAAAAAAAAAAAA= "/>
                <od:tableProperty name="DefaultView" type="2" value="2"/>
                <od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
                <od:tableProperty name="TotalsRow" type="1" value="0"/>
                <od:tableProperty name="FilterOnLoad" type="1" value="0"/>
                <od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
                <od:tableProperty name="HideNewField" type="1" value="0"/>
                <od:tableProperty name="BackTint" type="6" value="100"/>
                <od:tableProperty name="BackShade" type="6" value="100"/>
                <od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
                <od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
                <od:tableProperty name="AlternateBackTint" type="6" value="100"/>
                <od:tableProperty name="AlternateBackShade" type="6" value="100"/>
                <od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
                <od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="c_household_status_code" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="GUID" type="9" value="Zsrz7BUsEUeklHVIBcj6Zg== "/>
                            <od:fieldProperty name="ColumnWidth" type="3" value="2865"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="1"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="c_household_status_desc" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="GUID" type="9" value="6YhsWXOhL0GM12IctCbGqw== "/>
                            <od:fieldProperty name="ColumnWidth" type="3" value="2940"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="IMEMode" type="2" value="0"/>
                            <od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
                            <od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:maxLength value="255"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="c_household_status_desc_chn" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="GUID" type="9" value="UMvW04lKfEWLj6D7NUeiIg== "/>
                            <od:fieldProperty name="ColumnWidth" type="3" value="3195"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="IMEMode" type="2" value="0"/>
                            <od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
                            <od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:maxLength value="255"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== pleuston/eXistcbdb/accessfiles/HOUSEHOLD_STATUS_CODES.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="HOUSEHOLD_STATUS_CODES.xsd" generated="2013-11-25T16:40:31">
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>0</c_household_status_code>
        <c_household_status_desc>Unknown</c_household_status_desc>
        <c_household_status_desc_chn>未詳</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>1</c_household_status_code>
        <c_household_status_desc>Civilian household</c_household_status_desc>
        <c_household_status_desc_chn>民戶</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>2</c_household_status_code>
        <c_household_status_desc>Military household</c_household_status_desc>
        <c_household_status_desc_chn>軍戶</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>3</c_household_status_code>
        <c_household_status_desc>Artisan household</c_household_status_desc>
        <c_household_status_desc_chn>匠戶</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>4</c_household_status_code>
        <c_household_status_desc>Official household</c_household_status_desc>
        <c_household_status_desc_chn>官戶</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>5</c_household_status_code>
        <c_household_status_desc>Cook household</c_household_status_desc>
        <c_household_status_desc_chn>竈戶</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>6</c_household_status_code>
        <c_household_status_desc>Literary household</c_household_status_desc>
        <c_household_status_desc_chn>儒籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>7</c_household_status_code>
        <c_household_status_desc>Lishi household</c_household_status_desc>
        <c_household_status_desc_chn>力士籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>8</c_household_status_code>
        <c_household_status_desc>Yongshi household</c_household_status_desc>
        <c_household_status_desc_chn>勇士籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>9</c_household_status_code>
        <c_household_status_desc>Prophet household</c_household_status_desc>
        <c_household_status_desc_chn>占籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>10</c_household_status_code>
        <c_household_status_desc>Sijiaowei household</c_household_status_desc>
        <c_household_status_desc_chn>司校尉籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>11</c_household_status_code>
        <c_household_status_desc>Si household</c_household_status_desc>
        <c_household_status_desc_chn>司籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>12</c_household_status_code>
        <c_household_status_desc>Officer household</c_household_status_desc>
        <c_household_status_desc_chn>官藉</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>13</c_household_status_code>
        <c_household_status_desc>Wealthy household</c_household_status_desc>
        <c_household_status_desc_chn>富戶籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>14</c_household_status_code>
        <c_household_status_desc>Archer household</c_household_status_desc>
        <c_household_status_desc_chn>弓兵籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>15</c_household_status_code>
        <c_household_status_desc>Suo household</c_household_status_desc>
        <c_household_status_desc_chn>所籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>16</c_household_status_code>
        <c_household_status_desc>Qi household</c_household_status_desc>
        <c_household_status_desc_chn>旗籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>17</c_household_status_code>
        <c_household_status_desc>Jiaowei household</c_household_status_desc>
        <c_household_status_desc_chn>校尉籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>18</c_household_status_code>
        <c_household_status_desc>Jiao household</c_household_status_desc>
        <c_household_status_desc_chn>校籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>19</c_household_status_code>
        <c_household_status_desc>Zao household</c_household_status_desc>
        <c_household_status_desc_chn>灶籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>20</c_household_status_code>
        <c_household_status_desc>Shengyuan household</c_household_status_desc>
        <c_household_status_desc_chn>生員籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>21</c_household_status_code>
        <c_household_status_desc>Jian household</c_household_status_desc>
        <c_household_status_desc_chn>監籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>23</c_household_status_code>
        <c_household_status_desc>Zhan household</c_household_status_desc>
        <c_household_status_desc_chn>站籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>24</c_household_status_code>
        <c_household_status_desc>Wei household</c_household_status_desc>
        <c_household_status_desc_chn>衛籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>26</c_household_status_code>
        <c_household_status_desc>Doctor household</c_household_status_desc>
        <c_household_status_desc_chn>醫籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>27</c_household_status_code>
        <c_household_status_desc>Zhenfusi household</c_household_status_desc>
        <c_household_status_desc_chn>鎮撫司籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>28</c_household_status_code>
        <c_household_status_desc>Yinyang household</c_household_status_desc>
        <c_household_status_desc_chn>陰陽籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>29</c_household_status_code>
        <c_household_status_desc>Machuan household</c_household_status_desc>
        <c_household_status_desc_chn>馬船籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
    <HOUSEHOLD_STATUS_CODES>
        <c_household_status_code>30</c_household_status_code>
        <c_household_status_desc>Salt household</c_household_status_desc>
        <c_household_status_desc_chn>鹽籍</c_household_status_desc_chn>
    </HOUSEHOLD_STATUS_CODES>
</dataroot>
