=== pleuston/eXistcbdb/accessfiles/NIAN_HAO.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="dataroot">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="NIAN_HAO" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="generated" type="xsd:dateTime"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="NIAN_HAO">
        <xsd:annotation>
            <xsd:appinfo>
                <od:index index-name="PrimaryKey" index-key="c_nianhao_id " primary="yes" unique="yes" clustered="no" order="asc"/>
                <od:tableProperty name="Orientation" type="2" value="0"/>
                <od:tableProperty name="OrderByOn" type="1" value="0"/>
                <od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAXwcp6JYlmT7Rrppf3cnTrAAAAAFxeHLb+SeRAAAAAAAAAAABOAEkA QQBOAF8ASABBAE8AAAAAAAAAXQwuEcq/nkWqQG7is3a3nAcAAAAXwcp6JYlmT7Rr ppf3cnTrYwBfAG4AaQBhAG4AaABhAG8AXwBpAGQAAAAAAAAA/E72SfkS/kGxrOoV jcrotwcAAAAXwcp6JYlmT7Rrppf3cnTrYwBfAGQAeQAAAAAAAADo3Ft+fbSIRblX pHQQlkCFBwAAABfBynoliWZPtGuml/dydOtjAF8AZAB5AG4AYQBzAHQAeQBfAGMA aABuAAAAAAAAAHdys5cmuBBBhHRabhyk6XUHAAAAF8HKeiWJZk+0a6aX93J062MA XwBuAGkAYQBuAGgAYQBvAF8AYwBoAG4AAAAAAAAA3SuvbealhEqbuWg5HolyZgcA AAAXwcp6JYlmT7Rrppf3cnTrYwBfAG4AaQBhAG4AaABhAG8AXwBwAGkAbgAAAAAA AABbsEYAkvRdSozGVq1zmtATBwAAABfBynoliWZPtGuml/dydOtjAF8AZgBpAHIA cwB0AHkAZQBhAHIAAAAAAAAA+RTM5vFRqU6Gpp4Mc1dbTAcAAAAXwcp6JYlmT7Rr ppf3cnTrYwBfAGwAYQBzAHQAeQBlAGEAcgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA DAAAAAUAAAAAAAAAAAAAAAAAAAAAAA== "/>
                <od:tableProperty name="DefaultView" type="2" value="2"/>
                <od:tableProperty name="GUID" type="9" value="F8HKeiWJZk+0a6aX93J06w== "/>
                <od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
                <od:tableProperty name="TotalsRow" type="1" value="0"/>
                <od:tableProperty name="FilterOnLoad" type="1" value="0"/>
                <od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
                <od:tableProperty name="HideNewField" type="1" value="0"/>
                <od:tableProperty name="BackTint" type="6" value="100"/>
                <od:tableProperty name="BackShade" type="6" value="100"/>
                <od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
                <od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
                <od:tableProperty name="AlternateBackTint" type="6" value="100"/>
                <od:tableProperty name="AlternateBackShade" type="6" value="100"/>
                <od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
                <od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="c_nianhao_id" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="GUID" type="9" value="XQwuEcq/nkWqQG7is3a3nA== "/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="c_dy" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="GUID" type="9" value="/E72SfkS/kGxrOoVjcrotw== "/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="c_dynasty_chn" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="IMEMode" type="2" value="1"/>
                            <od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
                            <od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
                            <od:fieldProperty name="GUID" type="9" value="6Nxbfn20iEW5V6R0EJZAhQ== "/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:maxLength value="255"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="c_nianhao_chn" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="IMEMode" type="2" value="1"/>
                            <od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
                            <od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
                            <od:fieldProperty name="GUID" type="9" value="d3Kzlya4EEGEdFpuHKTpdQ== "/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:maxLength value="255"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="c_nianhao_pin" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="IMEMode" type="2" value="1"/>
                            <od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
                            <od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
                            <od:fieldProperty name="GUID" type="9" value="3SuvbealhEqbuWg5HolyZg== "/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:maxLength value="255"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="c_firstyear" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="GUID" type="9" value="W7BGAJL0XUqMxlatc5rQEw== "/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="c_lastyear" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
                            <od:fieldProperty name="ColumnOrder" type="3" value="0"/>
                            <od:fieldProperty name="ColumnHidden" type="1" value="0"/>
                            <od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
                            <od:fieldProperty name="Required" type="1" value="0"/>
                            <od:fieldProperty name="DisplayControl" type="3" value="109"/>
                            <od:fieldProperty name="GUID" type="9" value="+RTM5vFRqU6Gpp4Mc1dbTA== "/>
                            <od:fieldProperty name="TextAlign" type="2" value="0"/>
                            <od:fieldProperty name="AggregateType" type="4" value="-1"/>
                            <od:fieldProperty name="ResultType" type="2" value="0"/>
                            <od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== pleuston/eXistcbdb/accessfiles/NIAN_HAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NIAN_HAO.xsd" generated="2013-11-25T16:42:20">
    <NIAN_HAO>
        <c_nianhao_id>0</c_nianhao_id>
        <c_dy>0</c_dy>
        <c_dynasty_chn>未詳</c_dynasty_chn>
        <c_nianhao_chn>未詳</c_nianhao_chn>
        <c_nianhao_pin>unknown</c_nianhao_pin>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>1</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>建元</c_nianhao_chn>
        <c_firstyear>-140</c_firstyear>
        <c_lastyear>-135</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>2</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>元光</c_nianhao_chn>
        <c_firstyear>-134</c_firstyear>
        <c_lastyear>-129</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>3</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>元朔</c_nianhao_chn>
        <c_firstyear>-128</c_firstyear>
        <c_lastyear>-123</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>4</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>元狩</c_nianhao_chn>
        <c_firstyear>-122</c_firstyear>
        <c_lastyear>-117</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>5</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>元鼎</c_nianhao_chn>
        <c_firstyear>-116</c_firstyear>
        <c_lastyear>-111</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>6</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>元封</c_nianhao_chn>
        <c_firstyear>-110</c_firstyear>
        <c_lastyear>-105</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>7</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>太初</c_nianhao_chn>
        <c_firstyear>-104</c_firstyear>
        <c_lastyear>-101</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>8</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>天漢</c_nianhao_chn>
        <c_firstyear>-100</c_firstyear>
        <c_lastyear>-97</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>9</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>太始</c_nianhao_chn>
        <c_firstyear>-96</c_firstyear>
        <c_lastyear>-93</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>10</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>征和</c_nianhao_chn>
        <c_firstyear>-92</c_firstyear>
        <c_lastyear>-89</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>11</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>後元</c_nianhao_chn>
        <c_firstyear>-88</c_firstyear>
        <c_lastyear>-87</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>12</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>始元</c_nianhao_chn>
        <c_firstyear>-86</c_firstyear>
        <c_lastyear>-81</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>13</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>元鳳</c_nianhao_chn>
        <c_firstyear>-80</c_firstyear>
        <c_lastyear>-75</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>14</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>元平</c_nianhao_chn>
        <c_firstyear>-74</c_firstyear>
        <c_lastyear>-74</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>15</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>本始</c_nianhao_chn>
        <c_firstyear>-73</c_firstyear>
        <c_lastyear>-70</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>16</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>地節</c_nianhao_chn>
        <c_firstyear>-69</c_firstyear>
        <c_lastyear>-66</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>17</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>元康</c_nianhao_chn>
        <c_firstyear>-65</c_firstyear>
        <c_lastyear>-62</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>18</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>神爵</c_nianhao_chn>
        <c_firstyear>-61</c_firstyear>
        <c_lastyear>-58</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>19</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>五鳳</c_nianhao_chn>
        <c_firstyear>-57</c_firstyear>
        <c_lastyear>-54</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>20</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>甘露</c_nianhao_chn>
        <c_firstyear>-53</c_firstyear>
        <c_lastyear>-50</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>21</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>黃龍</c_nianhao_chn>
        <c_firstyear>-49</c_firstyear>
        <c_lastyear>-49</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>22</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>初元</c_nianhao_chn>
        <c_firstyear>-48</c_firstyear>
        <c_lastyear>-44</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>23</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>永光</c_nianhao_chn>
        <c_firstyear>-43</c_firstyear>
        <c_lastyear>-39</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>24</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>建昭</c_nianhao_chn>
        <c_firstyear>-38</c_firstyear>
        <c_lastyear>-34</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>25</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>竟寧</c_nianhao_chn>
        <c_firstyear>-33</c_firstyear>
        <c_lastyear>-33</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>26</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>建始</c_nianhao_chn>
        <c_firstyear>-32</c_firstyear>
        <c_lastyear>-29</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>27</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>河平</c_nianhao_chn>
        <c_firstyear>-28</c_firstyear>
        <c_lastyear>-25</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>28</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>陽朔</c_nianhao_chn>
        <c_firstyear>-24</c_firstyear>
        <c_lastyear>-21</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>29</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>鴻嘉</c_nianhao_chn>
        <c_firstyear>-20</c_firstyear>
        <c_lastyear>-17</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>30</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>永始</c_nianhao_chn>
        <c_firstyear>-16</c_firstyear>
        <c_lastyear>-13</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>31</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>元延</c_nianhao_chn>
        <c_firstyear>-12</c_firstyear>
        <c_lastyear>-9</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>32</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>綏和</c_nianhao_chn>
        <c_firstyear>-8</c_firstyear>
        <c_lastyear>-7</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>33</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>建平</c_nianhao_chn>
        <c_firstyear>-6</c_firstyear>
        <c_lastyear>-3</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>34</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>元壽</c_nianhao_chn>
        <c_firstyear>-2</c_firstyear>
        <c_lastyear>-1</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>35</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>元始</c_nianhao_chn>
        <c_firstyear>1</c_firstyear>
        <c_lastyear>5</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>36</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>居攝</c_nianhao_chn>
        <c_firstyear>6</c_firstyear>
        <c_lastyear>8</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>37</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
        <c_nianhao_chn>初始</c_nianhao_chn>
        <c_firstyear>8</c_firstyear>
        <c_lastyear>8</c_lastyear>
    </NIAN_HAO>
    <NIAN_HAO>
        <c_nianhao_id>38</c_nianhao_id>
        <c_dy>29</c_dy>
        <c_dynasty_chn>西漢</c_dynasty_chn>
